
CALENDAR__VIEW__HORIZONTAL_DAY = 'day-horizontal'
CALENDAR__VIEW__MONTH          = 'month'
CALENDAR__VIEW__VERTICAL_DAY   = 'day-vertical'
CALENDAR__VIEW__WEEK           = 'week'

CALENDAR__VIEW__HORIZONTAL     = 'horizontal'
CALENDAR__VIEW__VERTICAL       = 'vertical'

CALENDAR__VIEW__DAY_LAYOUT_TOGGLE = 4

CALENDAR__OFFICE_HRS__BREAK_TYPE      = 2
CALENDAR__OFFICE_HRS__OFFICE_HR_TYPE  = 1

CALENDAR__POS__PSEUDO     = 1
CALENDAR__POS__FULL_COVER = 2
CALENDAR__POS__TIMELINE   = 3

CACHE_PREFIX = '__cache__'

AUTH__ADMIN           = 1
AUTH__CLINIC_SETTINGS = 47
AUTH__MU_REPORT       = 46
AUTH__REPORTS         = 46
AUTH__SUPERBILL       = 33
AUTH__CALENDAR_SETUP  = 22
AUTH__NOTES           = 35
AUTH__PATIENT_CHART   = 34
AUTH__MESSAGES        = 32
AUTH__PATIENT_APPTS   = 31
AUTH__PATIENT_DEMO    = 30
AUTH__READ            = 1
AUTH__WRITE           = 2

KEYBOARD__EVENT_DOWN_ARROW = 40
KEYBOARD__EVENT_ENTER      = 13
KEYBOARD__EVENT_UP_ARROW   = 38

TIMEOUT__LOADER_CLOSE_DELAY = 250

ONE_DAY_SECONDS = 24 * 60 * 60
DAY_IN_MS = 86400000

FT_DARK_NON_PROVIDER_CALENDARS = 'dark-feature.non-provider-calendars'
FT_DARK_PATIENT_ALERTS = 'dark-feature.dashboard-patient-alerts'
FT_DARK_DASHBOARD_PATIENT_PHOTOS = 'dark-feature.dashboard-patient-photos'
FT_CLINICAL_FEATURE = 'feature-set.clinical'
